<?php

namespace Tests\Feature\Website\Gallery;

use App\Enums\Website\WebsiteAssetPurpose;
use App\Library\Website\Gallery\WebsiteGalleryManager;
use App\Models\WebsiteAsset;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Feature\Website\Concerns\CreatesWebsiteFixtures;
use Tests\TestCase;

/**
 * Website Builder redesign — proves the v1 gallery step's reorder/cover
 * mechanics (multi-upload itself just loops the already-tested
 * WebsiteAssetUploadService, so is not re-proven here).
 */
class WebsiteGalleryManagerTest extends TestCase
{
    use RefreshDatabase;
    use CreatesWebsiteFixtures;

    private function asset($website, int $sortOrder = 0, WebsiteAssetPurpose $purpose = WebsiteAssetPurpose::Gallery): WebsiteAsset
    {
        return WebsiteAsset::create([
            'website_id' => $website->id,
            'disk' => 'public',
            'path' => 'images/websites/' . $website->uid . '/' . uniqid('', true) . '.png',
            'mime_type' => 'image/png',
            'size' => 1024,
            'sort_order' => $sortOrder,
            'purpose' => $purpose->value,
        ]);
    }

    public function test_reorder_rewrites_every_assets_sort_order_to_the_given_position(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        $a = $this->asset($website, 0);
        $b = $this->asset($website, 1);
        $c = $this->asset($website, 2);

        app(WebsiteGalleryManager::class)->reorder($website, WebsiteAssetPurpose::Gallery, [$c->uid, $a->uid, $b->uid]);

        $this->assertSame(0, $c->fresh()->sort_order);
        $this->assertSame(1, $a->fresh()->sort_order);
        $this->assertSame(2, $b->fresh()->sort_order);
    }

    public function test_reorder_refuses_a_list_missing_one_of_the_websites_assets(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        $a = $this->asset($website, 0);
        $this->asset($website, 1);

        $this->expectException(\App\Exceptions\Website\InvalidWebsiteAssetException::class);
        app(WebsiteGalleryManager::class)->reorder($website, WebsiteAssetPurpose::Gallery, [$a->uid]);
    }

    public function test_reorder_refuses_a_foreign_assets_uid(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        [, $otherBusiness] = $this->entitledTenant();
        $otherWebsite = $this->createWebsite($otherBusiness);
        $foreign = $this->asset($otherWebsite, 0);
        $mine = $this->asset($website, 0);

        $this->expectException(\App\Exceptions\Website\InvalidWebsiteAssetException::class);
        app(WebsiteGalleryManager::class)->reorder($website, WebsiteAssetPurpose::Gallery, [$foreign->uid]);
    }

    public function test_setting_a_cover_clears_any_prior_cover(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        $a = $this->asset($website, 0);
        $b = $this->asset($website, 1);
        $manager = app(WebsiteGalleryManager::class);

        $manager->setCover($website, $a);
        $this->assertTrue($a->fresh()->is_cover);

        $manager->setCover($website, $b);
        $this->assertFalse($a->fresh()->is_cover, 'Setting a new cover must clear the prior one — only one cover at a time.');
        $this->assertTrue($b->fresh()->is_cover);
    }

    public function test_setting_a_cover_on_a_foreign_asset_is_refused(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        [, $otherBusiness] = $this->entitledTenant();
        $otherWebsite = $this->createWebsite($otherBusiness);
        $foreign = $this->asset($otherWebsite, 0);

        $this->expectException(\Symfony\Component\HttpKernel\Exception\NotFoundHttpException::class);
        app(WebsiteGalleryManager::class)->setCover($website, $foreign);
    }

    /**
     * Independent-review correction round 2 — updating title/category
     * must refresh an AUTOGENERATED alt text (never one the owner
     * explicitly typed) so the deterministic policy stays truthful after
     * metadata changes.
     */
    public function test_updating_title_refreshes_an_autogenerated_alt_text(): void
    {
        [, $business] = $this->entitledTenant(['name' => 'Snap Booth Co']);
        $website = $this->createWebsite($business);
        $asset = $this->asset($website);
        $asset->forceFill(['alt_text' => 'Snap Booth Co', 'alt_text_is_custom' => false])->save();

        app(WebsiteGalleryManager::class)->setTitleAndCategory($website, $asset, WebsiteAssetPurpose::Gallery, 'Open-air booth in action', null);

        $this->assertSame('Open-air booth in action', $asset->fresh()->alt_text);
        $this->assertFalse($asset->fresh()->alt_text_is_custom);
    }

    public function test_an_explicit_user_alt_text_is_never_overwritten_by_a_later_metadata_update(): void
    {
        [, $business] = $this->entitledTenant();
        $website = $this->createWebsite($business);
        $asset = $this->asset($website);

        app(WebsiteGalleryManager::class)->setTitleAndCategory($website, $asset, WebsiteAssetPurpose::Gallery, 'Some title', null, 'My own hand-written alt text');
        $this->assertSame('My own hand-written alt text', $asset->fresh()->alt_text);
        $this->assertTrue($asset->fresh()->alt_text_is_custom);

        // A LATER metadata update with no new custom alt text must leave
        // the owner's own explicit text alone.
        app(WebsiteGalleryManager::class)->setTitleAndCategory($website, $asset->fresh(), WebsiteAssetPurpose::Gallery, 'A different title', 'a-category');

        $this->assertSame('My own hand-written alt text', $asset->fresh()->alt_text, 'An explicitly user-edited alt text must never be silently regenerated.');
    }
}
