<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Independent-review correction round 2 — the deterministic alt-text
 * policy must stay truthful as metadata changes: updating a photo's
 * title/category should refresh an AUTOGENERATED alt text, but must
 * never clobber one the owner explicitly typed themselves. This flag is
 * the only source of truth for which case applies; it is never
 * customer-editable directly, only flipped true the moment an owner
 * submits a non-blank alt_text value in the gallery metadata form.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('website_assets', function (Blueprint $table): void {
            $table->boolean('alt_text_is_custom')->default(false)->after('alt_text');
        });
    }

    public function down(): void
    {
        Schema::table('website_assets', function (Blueprint $table): void {
            $table->dropColumn('alt_text_is_custom');
        });
    }
};
