<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Independent-review correction round 3 — the round-2 migration defaulted
 * EVERY existing website_assets row's new `alt_text_is_custom` column to
 * false, including rows whose alt_text was typed by a human through the
 * pre-existing (pre-wizard) `WebsiteController::storeAsset()` upload form,
 * which has always accepted a caller-supplied `alt_text` verbatim
 * (`$this->assetUploads->store($website, $request->file('image'),
 * $request->input('alt_text'))`). Left as `false`, a later metadata edit
 * through the wizard's own gallery step (WebsiteGalleryManager::
 * setTitleAndCategory()) would silently regenerate and overwrite that
 * historical, human-authored text.
 *
 * No column exists (and never existed) that marks WHICH historical rows
 * were autogenerated — automatic alt-text suggestion
 * (WebsiteAssetAltTextGenerator) is itself a round-2 addition, newer than
 * any row this migration backfills. Absent any durable evidence that a
 * row was machine-generated, the only safe assumption is that a
 * pre-existing non-blank alt_text was written by a person, so it is
 * marked custom here and permanently protected from a later silent
 * overwrite. A blank alt_text carries no such risk (there is nothing to
 * protect) and is left alone.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::table('website_assets')
            ->where('alt_text_is_custom', false)
            ->whereNotNull('alt_text')
            ->where('alt_text', '!=', '')
            ->update(['alt_text_is_custom' => true]);
    }

    public function down(): void
    {
        // Deliberately irreversible: this is a one-way data-safety
        // backfill, never a schema change — there is no way to recover
        // which rows were true false-positives without the very evidence
        // this migration establishes did not exist.
    }
};
