<?php

namespace Tests\Feature\Calendar;

use App\Enums\Calendar\AppointmentStatus;
use App\Enums\Calendar\ExternalCalendarConnectionState;
use App\Enums\Calendar\ExternalCalendarProvider;
use App\Models\Appointment;
use App\Models\BookingContactIdentityLock;
use App\Models\BookingType;
use App\Models\BookingTypeRoundRobinState;
use App\Models\ExternalCalendarBusyBlock;
use App\Models\ExternalCalendarConnection;
use App\Models\StaffAvailabilityRule;
use App\Models\StaffBookingLock;
use App\Models\StaffTimeOff;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Tests\Feature\Calendar\Concerns\CreatesCalendarTestData;
use Tests\TestCase;

/**
 * Implementation Contract 15 §12.A — the Sub-slice A models carry casts and
 * relations only. These are smoke tests for exactly that surface: no
 * manager, service, controller or route exists yet, and none is exercised.
 */
class CalendarModelSmokeTest extends TestCase
{
    use RefreshDatabase;
    use CreatesCalendarTestData;

    private function assertIsRealUuid(string $value, string $label): void
    {
        $this->assertTrue(
            Str::isUuid($value),
            "[{$label}] must be a real UUID, got [{$value}] — HasUid's uniqid() default was not overridden."
        );
    }

    // --- BookingType ---

    /**
     * §5.1 — HasUid's default generateUid() is uniqid(), which is neither a
     * valid UUID nor safe for anything security-adjacent. Every Schema A
     * model that uses the trait overrides it.
     */
    public function test_booking_type_generates_a_real_uuid_uid_not_a_uniqid(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);

        $bookingType = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'Consultation',
            'duration_minutes' => 30,
        ]);

        $this->assertIsRealUuid($bookingType->uid, 'booking_types.uid');
    }

    /**
     * §5.1 — public_booking_uuid is generated by the model's OWN booted()
     * creating hook, independent of HasUid's hook, and is a DIFFERENT value
     * from uid. Both must be real UUIDs.
     */
    public function test_booking_type_generates_a_distinct_public_booking_uuid(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);

        $bookingType = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'Consultation',
            'duration_minutes' => 30,
        ]);

        $this->assertIsRealUuid($bookingType->public_booking_uuid, 'booking_types.public_booking_uuid');
        $this->assertNotSame(
            $bookingType->uid,
            $bookingType->public_booking_uuid,
            'The public address must never be the same value as the internal uid.'
        );
    }

    public function test_two_booking_types_never_share_a_public_booking_uuid(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);

        $first = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'A',
            'duration_minutes' => 15,
        ]);
        $second = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'B',
            'duration_minutes' => 45,
        ]);

        $this->assertNotSame($first->public_booking_uuid, $second->public_booking_uuid);
    }

    /**
     * §5.1 — the public address is generated, never supplied by a caller or
     * a request, so it must not be mass-assignable.
     */
    public function test_public_booking_uuid_is_not_mass_assignable(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);
        $attempted = (string) Str::uuid();

        $bookingType = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'Consultation',
            'duration_minutes' => 30,
            'public_booking_uuid' => $attempted,
        ]);

        $this->assertNotSame($attempted, $bookingType->public_booking_uuid);
        $this->assertIsRealUuid($bookingType->public_booking_uuid, 'booking_types.public_booking_uuid');
    }

    public function test_booking_type_casts_and_relations(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);
        $staff = $this->staffUser();

        $bookingType = BookingType::create([
            'business_location_id' => $location->id,
            'name' => 'Consultation',
            'duration_minutes' => 30,
            'is_active' => true,
        ]);

        $this->assertIsBool($bookingType->is_active);
        $this->assertIsInt($bookingType->duration_minutes);
        $this->assertTrue($bookingType->isActive());
        $this->assertSame($location->id, $bookingType->location->id);

        $bookingType->staff()->attach($staff->id);
        $this->assertTrue($bookingType->staff()->where('users.id', $staff->id)->exists());

        $state = BookingTypeRoundRobinState::create(['booking_type_id' => $bookingType->id]);
        $this->assertSame($state->id, $bookingType->refresh()->roundRobinState->id);
    }

    // --- Appointment ---

    public function test_appointment_casts_status_to_the_enum_and_generates_a_uuid(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);
        $staff = $this->staffUser();
        $bookingTypeId = $this->insertBookingType($location);
        $contactId = $this->insertContact($business, $location);

        $appointment = Appointment::create([
            'business_location_id' => $location->id,
            'booking_type_id' => $bookingTypeId,
            'staff_user_id' => $staff->id,
            'contact_id' => $contactId,
            'status' => AppointmentStatus::Scheduled,
            'start_at' => now()->addDay(),
            'end_at' => now()->addDay()->addMinutes(30),
        ]);

        $this->assertIsRealUuid($appointment->uid, 'appointments.uid');
        $this->assertSame(AppointmentStatus::Scheduled, $appointment->refresh()->status);
        $this->assertTrue($appointment->isScheduled());
        $this->assertInstanceOf(Carbon::class, $appointment->start_at);
        $this->assertIsInt($appointment->reschedule_count);

        $this->assertSame($location->id, $appointment->location->id);
        $this->assertSame($bookingTypeId, $appointment->bookingType->id);
        $this->assertSame($staff->id, $appointment->staff->id);
        $this->assertSame($contactId, $appointment->contact->id);
        $this->assertNull($appointment->crmOpportunity);
        $this->assertNull($appointment->createdBy);
    }

    /**
     * §5.4/§7.4 — `scheduled` is the only non-terminal state.
     */
    public function test_appointment_status_enum_marks_the_three_outcomes_terminal(): void
    {
        $this->assertFalse(AppointmentStatus::Scheduled->isTerminal());
        $this->assertTrue(AppointmentStatus::Cancelled->isTerminal());
        $this->assertTrue(AppointmentStatus::Completed->isTerminal());
        $this->assertTrue(AppointmentStatus::NoShow->isTerminal());

        $this->assertSame(
            ['scheduled', 'cancelled', 'completed', 'no_show'],
            array_map(static fn (AppointmentStatus $case): string => $case->value, AppointmentStatus::cases())
        );
    }

    // --- ExternalCalendarConnection ---

    public function test_connection_casts_provider_and_state_to_enums(): void
    {
        $staff = $this->staffUser();

        $connection = ExternalCalendarConnection::create([
            'user_id' => $staff->id,
            'provider' => ExternalCalendarProvider::Google,
            'state' => ExternalCalendarConnectionState::Pending,
        ]);

        $fresh = $connection->refresh();

        $this->assertIsRealUuid($fresh->uid, 'external_calendar_connections.uid');
        $this->assertSame(ExternalCalendarProvider::Google, $fresh->provider);
        $this->assertSame(ExternalCalendarConnectionState::Pending, $fresh->state);
        $this->assertSame($staff->id, $fresh->user->id);
        $this->assertTrue($fresh->occupiesConnectionSlot());
    }

    /**
     * §5.5 — the refresh token is encrypted at rest with Laravel's built-in
     * `encrypted` cast, the same precedent BusinessGoogleConnection uses.
     * Proven by reading the RAW column, not the model attribute.
     */
    public function test_refresh_token_is_encrypted_at_rest_and_readable_through_the_cast(): void
    {
        $staff = $this->staffUser();
        $plaintext = 'refresh-token-' . Str::random(24);

        $connection = ExternalCalendarConnection::create([
            'user_id' => $staff->id,
            'provider' => ExternalCalendarProvider::Google,
            'state' => ExternalCalendarConnectionState::Active,
            'refresh_token_encrypted' => $plaintext,
        ]);

        $raw = DB::table('external_calendar_connections')->where('id', $connection->id)->value('refresh_token_encrypted');

        $this->assertNotSame($plaintext, $raw, 'The refresh token must never be stored in plaintext.');
        $this->assertStringNotContainsString($plaintext, (string) $raw);
        $this->assertSame($plaintext, $connection->refresh()->refresh_token_encrypted);
    }

    /**
     * §5.5 — defence in depth: an accidental toArray()/toJson() must not
     * leak the credential or the OAuth nonce.
     */
    public function test_credentials_are_hidden_from_serialization(): void
    {
        $staff = $this->staffUser();

        $connection = ExternalCalendarConnection::create([
            'user_id' => $staff->id,
            'provider' => ExternalCalendarProvider::Google,
            'state' => ExternalCalendarConnectionState::Active,
            'refresh_token_encrypted' => 'secret-value',
            'oauth_state_nonce' => (string) Str::uuid(),
        ]);

        $serialized = $connection->toArray();

        $this->assertArrayNotHasKey('refresh_token_encrypted', $serialized);
        $this->assertArrayNotHasKey('oauth_state_nonce', $serialized);
        $this->assertStringNotContainsString('secret-value', $connection->toJson());
    }

    /**
     * §5.5 — the two slot-occupying states, kept in step with the generated
     * column's own CASE expression.
     */
    public function test_connection_state_enum_agrees_with_the_generated_column(): void
    {
        $this->assertTrue(ExternalCalendarConnectionState::Pending->occupiesConnectionSlot());
        $this->assertTrue(ExternalCalendarConnectionState::Active->occupiesConnectionSlot());
        $this->assertFalse(ExternalCalendarConnectionState::Disconnected->occupiesConnectionSlot());
        $this->assertFalse(ExternalCalendarConnectionState::Revoked->occupiesConnectionSlot());

        $staff = $this->staffUser();
        $connection = ExternalCalendarConnection::create([
            'user_id' => $staff->id,
            'provider' => ExternalCalendarProvider::Outlook,
            'state' => ExternalCalendarConnectionState::Disconnected,
            'disconnected_at' => now(),
        ]);

        $this->assertFalse($connection->refresh()->occupiesConnectionSlot());
        $this->assertNull(
            DB::table('external_calendar_connections')->where('id', $connection->id)->value('active_user_id')
        );
    }

    public function test_busy_block_belongs_to_its_connection(): void
    {
        $staff = $this->staffUser();
        $connection = ExternalCalendarConnection::create([
            'user_id' => $staff->id,
            'provider' => ExternalCalendarProvider::Google,
            'state' => ExternalCalendarConnectionState::Active,
        ]);

        $block = ExternalCalendarBusyBlock::create([
            'external_calendar_connection_id' => $connection->id,
            'provider_event_id' => 'evt-1',
            'start_at' => now(),
            'end_at' => now()->addHour(),
            'synced_at' => now(),
        ]);

        $this->assertInstanceOf(Carbon::class, $block->start_at);
        $this->assertSame($connection->id, $block->connection->id);
        $this->assertTrue($connection->refresh()->busyBlocks->contains($block->id));
    }

    // --- availability, time off, locks ---

    /**
     * §5.2 — start_time/end_time are LOCAL time-of-day and are deliberately
     * NOT cast to datetime: a cast would invent a date and an offset the
     * column does not carry, which is the DST corruption the contract
     * forbids.
     */
    public function test_availability_rule_keeps_local_times_as_plain_strings(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);
        $staff = $this->staffUser();

        $rule = StaffAvailabilityRule::create([
            'business_location_id' => $location->id,
            'staff_user_id' => $staff->id,
            'day_of_week' => 3,
            'start_time' => '09:00:00',
            'end_time' => '17:00:00',
        ]);

        $fresh = $rule->refresh();

        $this->assertIsString($fresh->start_time);
        $this->assertSame('09:00:00', $fresh->start_time);
        $this->assertIsInt($fresh->day_of_week);
        $this->assertSame($staff->id, $fresh->staff->id);
        $this->assertSame($location->id, $fresh->location->id);
    }

    public function test_staff_time_off_is_user_scoped_with_utc_timestamps(): void
    {
        $staff = $this->staffUser();

        $timeOff = StaffTimeOff::create([
            'staff_user_id' => $staff->id,
            'start_at' => now()->addDays(2),
            'end_at' => now()->addDays(4),
            'reason' => 'Annual leave',
        ]);

        $fresh = $timeOff->refresh();

        $this->assertSame('staff_time_off', $fresh->getTable());
        $this->assertInstanceOf(Carbon::class, $fresh->start_at);
        $this->assertSame($staff->id, $fresh->staff->id);
        $this->assertNull($fresh->createdBy);
    }

    /**
     * §7.2 — the lock row's key IS staff_user_id; it has no auto-increment
     * id of its own.
     */
    public function test_staff_booking_lock_is_keyed_on_the_staff_user(): void
    {
        $staff = $this->staffUser();

        $lock = StaffBookingLock::create(['staff_user_id' => $staff->id]);

        $this->assertSame('staff_user_id', $lock->getKeyName());
        $this->assertFalse($lock->incrementing);
        $this->assertSame($staff->id, $lock->refresh()->staff->id);
    }

    public function test_contact_identity_lock_relates_to_its_location(): void
    {
        $business = $this->calendarBusiness();
        $location = $this->calendarLocation($business);

        $lock = BookingContactIdentityLock::create([
            'business_location_id' => $location->id,
            'normalized_phone' => '14155551234',
        ]);

        $this->assertSame($location->id, $lock->refresh()->location->id);
    }
}
