<?php

namespace Tests\Feature\Usage;

use App\Enums\Entitlement\WorkspacePlanTier;
use App\Library\Entitlement\EntitlementManager;
use App\Library\Usage\Contracts\PaymentProviderGateway;
use App\Library\Usage\FakePaymentProviderGateway;
use App\Library\Usage\PaymentMethodResult;
use App\Library\Usage\UsageBillingCheckoutManager;
use App\Models\Currency;
use App\Models\User;
use App\Models\Workspace;
use App\Repositories\Contracts\AdditionalBusinessSlotAgreementRepository;
use App\Repositories\Contracts\AdditionalBusinessSlotRenewalChargeRepository;
use App\Repositories\Contracts\PaymentProviderCustomerRepository;
use App\Repositories\Contracts\WorkspacePlanCatalogRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use Tests\TestCase;

/**
 * M4 contract §11/§21 (Correction Round 1 §C) — strengthened: a
 * change_operation_id is caller-supplied and never generated/overwritten
 * by requestSlotAgreementIncrease() itself; a genuine retry (identical
 * change_operation_id) reuses the identical local_idempotency_key and is
 * absorbed as a no-op, never reserving another delta or advancing
 * target_allocation_count a second time; two distinct pending increases
 * reserve deltas from the locked target_allocation_count, never the
 * stale current_allocation_count.
 */
class AdditionalBusinessSlotAgreementRepeatedIncreaseTest extends TestCase
{
    use RefreshDatabase;

    private FakePaymentProviderGateway $gateway;

    private int $currencyId;

    protected function setUp(): void
    {
        parent::setUp();

        $this->currencyId = Currency::create(['name' => 'US Dollar', 'code' => 'USD', 'format' => '$', 'status' => true])->id;
        $this->gateway = new FakePaymentProviderGateway();
        app()->instance(PaymentProviderGateway::class, $this->gateway);
    }

    private function completedAgreement(): array
    {
        $owner = User::create([
            'first_name' => 'Fixture', 'last_name' => 'Owner', 'email' => 'owner'.uniqid().'@example.test',
            'status' => true, 'is_admin' => false, 'is_customer' => true, 'active_portal' => 'customer',
        ]);
        $admin = User::create([
            'first_name' => 'Fixture', 'last_name' => 'Admin', 'email' => 'admin'.uniqid().'@example.test',
            'status' => true, 'is_admin' => true, 'is_customer' => false, 'active_portal' => 'admin',
        ]);
        $workspace = Workspace::create(['name' => 'Test Workspace', 'owner_user_id' => $owner->id, 'is_active' => true]);
        $catalog = app(WorkspacePlanCatalogRepository::class)->findByTier(WorkspacePlanTier::Core);
        app(EntitlementManager::class)->updateCatalogPricing($catalog, '20.00', $this->currencyId, '0.5000', $admin->id, 'Fixture pricing.');
        app(EntitlementManager::class)->assignFirstPlan($workspace, WorkspacePlanTier::Core, $admin->id, 'Fixture.', false, 0);

        $manager = app(UsageBillingCheckoutManager::class);
        $quote = $manager->quoteAdditionalSlotAgreement($workspace, 1, $owner->id);
        $agreement = app(AdditionalBusinessSlotAgreementRepository::class)->findById($quote->agreementId);
        $manager->initiateSlotAgreementCheckout($agreement, $owner->id);
        $agreement = app(AdditionalBusinessSlotAgreementRepository::class)->findById($agreement->id);
        $providerCustomer = app(PaymentProviderCustomerRepository::class)->findActiveByWorkspaceId((int) $workspace->id);
        $this->gateway->registerPaymentMethod(new PaymentMethodResult('pm_fake_initial', $providerCustomer->provider_customer_id, 'card', 'visa', '4242', 12, 2030));
        $this->gateway->checkoutSessionOutcomes[$agreement->local_idempotency_key] = ['providerPaymentMethodId' => 'pm_fake_initial'];
        $manager->confirmSlotAgreementFromReturn($agreement);

        return [$workspace, $owner, app(AdditionalBusinessSlotAgreementRepository::class)->findById($agreement->id)];
    }

    public function test_a_genuine_retry_with_the_same_change_operation_id_reuses_the_identical_charge(): void
    {
        [, $owner, $agreement] = $this->completedAgreement();
        $manager = app(UsageBillingCheckoutManager::class);
        $changeOperationId = (string) Str::uuid();

        // Core's own [0,1,2] additional-slot cap (RFC-004) leaves room for
        // exactly one more slot above the 1 already allocated.
        $first = $manager->requestSlotAgreementIncrease($agreement, 2, $changeOperationId, $owner->id);
        $refreshed = app(AdditionalBusinessSlotAgreementRepository::class)->findById((int) $agreement->id);

        // A retry: identical change_operation_id, never regenerated by
        // the caller here (matching the view's own one-UUID-per-render
        // contract).
        $second = $manager->requestSlotAgreementIncrease($refreshed, 2, $changeOperationId, $owner->id);

        $this->assertSame($first->renewalChargeId, $second->renewalChargeId);
        $this->assertSame(1, \Illuminate\Support\Facades\DB::table('additional_business_slot_renewal_charges')->where('change_operation_id', $changeOperationId)->count());

        $finalAgreement = app(AdditionalBusinessSlotAgreementRepository::class)->findById((int) $agreement->id);
        $this->assertSame(2, $finalAgreement->target_allocation_count);
    }

    public function test_two_distinct_pending_increases_reserve_deltas_from_the_locked_target_never_the_stale_current(): void
    {
        [, $owner, $agreement] = $this->completedAgreement();
        $manager = app(UsageBillingCheckoutManager::class);

        // Both attempts remain provider-pending/requires_action (never
        // resolved to Succeeded), so current_allocation_count stays at 2
        // throughout — the exact scenario proving the reservation must
        // key off target_allocation_count, not current_allocation_count.
        $this->gateway->paymentIntentOutcomes['*'] = 'requires_action';

        $first = $manager->requestSlotAgreementIncrease($agreement, 3, (string) Str::uuid(), $owner->id);
        $refreshed = app(AdditionalBusinessSlotAgreementRepository::class)->findById((int) $agreement->id);
        $this->assertSame(3, $refreshed->target_allocation_count);

        $second = $manager->requestSlotAgreementIncrease($refreshed, 4, (string) Str::uuid(), $owner->id);
        $finalAgreement = app(AdditionalBusinessSlotAgreementRepository::class)->findById((int) $agreement->id);
        $this->assertSame(4, $finalAgreement->target_allocation_count);

        $firstCharge = app(AdditionalBusinessSlotRenewalChargeRepository::class)->findById($first->renewalChargeId);
        $secondCharge = app(AdditionalBusinessSlotRenewalChargeRepository::class)->findById($second->renewalChargeId);

        // current 1 -> target 3 (delta 2); then locked target 3 -> 4 (delta 1).
        $this->assertSame(2, $firstCharge->allocation_delta);
        $this->assertSame(1, $secondCharge->allocation_delta);
    }

    public function test_a_non_increasing_target_is_rejected(): void
    {
        [, $owner, $agreement] = $this->completedAgreement();

        $this->expectException(\App\Exceptions\Usage\UnauthorizedSlotAgreementActionException::class);
        app(UsageBillingCheckoutManager::class)->requestSlotAgreementIncrease($agreement, 1, (string) Str::uuid(), $owner->id);
    }
}
