{{--
    Unified Business Home §2.5 (H-3) — Business performance.

    The period is the customer's own choice, through the SAME range control
    Results uses, and the three figures are the only canonical ones: new
    contacts, new conversations and messages received. Each sits beside its
    comparison with the equal-length period immediately before it, described
    and never praised — a rise in any of them is a factual change, not a win.

    The chart is fetched by the browser from B5's own series endpoint for the
    same range: this page renders no series of its own. "See details" opens
    Results on that same period.
--}}
<section class="mb-2" aria-labelledby="dashboard-headlines-heading" data-band="headlines" data-range="{{ $headlines['range']->cacheKey() }}">
    <x-card>
        <div class="d-flex flex-wrap justify-content-between align-items-center gap-1 mb-50">
            <h2 class="h4 text-section-heading mb-0" id="dashboard-headlines-heading">Business performance</h2>
            @if($headlines['resultsUrl'])
                <x-button variant="outline" size="sm" :href="$headlines['resultsUrl']" data-role="results-link">See details</x-button>
            @endif
        </div>

        <div class="mb-1" data-role="performance-range">
            @include('customer.business.analytics._range', [
                'range' => $headlines['range'],
                'formAction' => $headlines['formAction'],
            ])
        </div>

        @if($headlines['rangeRejected'])
            <p class="text-caption mb-1" data-role="range-rejected">
                That date range can't be used, so this shows {{ strtolower($headlines['range']->label()) }} instead.
            </p>
        @endif

        <p class="text-caption text-muted mb-2" data-role="headline-period">
            {{ $headlines['currentLabel'] }}, compared with the {{ $headlines['previousRange']->days() }} days before it ({{ $headlines['previousLabel'] }}).
        </p>

        <div class="row g-2">
            @foreach($headlines['items'] as $headline)
                <div class="col-12 col-sm-6 col-xl-4">
                    <article class="border rounded p-1 h-100" data-role="headline" data-headline="{{ $headline->key }}"
                             data-trend="{{ $headline->comparison->trend->value }}" data-polarity="{{ $headline->polarity->value }}"
                             @if($headline->judgement !== null) data-judgement="{{ $headline->judgement }}" @endif>
                        <h3 class="h6 text-label mb-50">{{ $headline->label }}</h3>
                        <p class="h2 mb-0" data-role="headline-figure">{{ $headline->figure }}</p>
                        <p class="text-caption text-muted mb-50">{{ $headline->figureCaption }}</p>
                        <p class="mb-50" data-role="headline-comparison">{{ $headline->comparisonSentence }}</p>
                        @if($headline->judgementWord() !== null)
                            <x-badge :variant="$headline->judgementVariant()" class="mb-50" data-role="headline-judgement">{{ $headline->judgementWord() }}</x-badge>
                        @endif
                        <p class="text-caption mb-0" data-role="headline-interpretation">{{ $headline->interpretation }}</p>
                    </article>
                </div>
            @endforeach
        </div>

        @if($headlines['seriesUrl'])
            <div class="mt-2">
                <h3 class="h6 text-label mb-50" id="dashboard-contacts-chart-heading">New contacts</h3>
                <div data-role="chart-new-contacts" data-series-url="{{ $headlines['seriesUrl'] }}"
                     aria-labelledby="dashboard-contacts-chart-heading" role="img" style="min-height: 180px;">
                    <p class="text-caption text-muted mb-0" data-role="chart-placeholder">Loading the chart…</p>
                </div>
            </div>
        @endif

        {{-- Unified Business Home §2.5 (AI-3) — "What we notice". Only a cached,
             displayable, validated insight; never generated by this page. It
             is labelled "AI summary", every statement carries its certainty as
             a plain word, and it stays apart from the deterministic "Why this?". --}}
        @if(($headlines['insight'] ?? null) !== null)
            <div class="mt-2 pt-2 border-top" data-role="what-we-notice">
                <div class="d-flex flex-wrap align-items-baseline justify-content-between gap-50 mb-50">
                    <h3 class="h6 text-label mb-0" id="dashboard-what-we-notice-heading">What we notice</h3>
                    <p class="text-caption text-muted mb-0">
                        <span data-role="ai-summary-label">AI summary</span>
                        · <span data-role="insight-updated">{{ $headlines['insight']['updated'] }}</span>
                    </p>
                </div>
                <ul class="list-unstyled mb-0" aria-labelledby="dashboard-what-we-notice-heading" data-role="insight-statements">
                    @foreach($headlines['insight']['statements'] as $statement)
                        <li class="mb-50" data-role="insight-statement" data-class="{{ $statement['class'] }}">
                            <strong data-role="insight-certainty">{{ $statement['label'] }}:</strong>
                            <span>{{ $statement['text'] }}</span>
                        </li>
                    @endforeach
                </ul>
            </div>
        @endif

        {{-- §8.2 E-4 — the customer's own single-shot "Explain this change". --}}
        @if(($headlines['explain'] ?? null) !== null)
            <div class="mt-2" data-role="explain-this-change">
                @if($headlines['explain']['requested'])
                    <p class="text-caption text-muted mb-0" data-role="explain-requested">An explanation of this change was requested. It will appear here when it's ready.</p>
                @else
                    <form method="POST" action="{{ $headlines['explain']['action'] }}" class="d-inline" data-role="explain-form">
                        @csrf
                        @foreach($headlines['explain']['range'] as $name => $value)
                            <input type="hidden" name="{{ $name }}" value="{{ $value }}">
                        @endforeach
                        <x-button type="submit" variant="outline" size="sm" data-role="explain-button">Explain this change</x-button>
                    </form>
                @endif
            </div>
        @endif
    </x-card>
</section>
