<?php

namespace App\Http\Controllers\Customer\Business;

use App\Exceptions\MetaAds\MetaAdsMutationConnectionException;
use App\Exceptions\MetaAds\MetaAdsMutationException;
use App\Http\Controllers\Customer\Business\Concerns\ResolvesBusinessTenancy;
use App\Http\Controllers\Customer\Business\Concerns\ResolvesMetaAdsBusinessTenancy;
use App\Http\Controllers\Customer\CustomerBaseController;
use App\Library\MetaAds\Mutations\MetaAdsMutationOutcome;
use App\Library\MetaAds\Mutations\MetaAdsMutationOutcomeStatus;
use App\Library\MetaAds\Mutations\MetaAdsMutationService;
use App\Library\MetaAds\Reporting\MetaAdsListInput;
use App\Library\Workspace\WorkspaceManager;
use App\Models\Business;
use App\Repositories\Contracts\WorkspaceRepository;
use Closure;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Meta Ads Module V1 contract 24 §7 — the HTTP side of pause / resume.
 *
 * THIN: every action is one MetaAdsMutationService call; this class only
 * resolves tenancy, checks `manage_meta_ads`, maps the outcome to a calm flash
 * and redirects. It never builds a provider request.
 *
 * Order (as everywhere in the module): tenancy + full-Ads-module entitlement
 * (404), THEN `manage_meta_ads` (the application's 401), then the service,
 * which re-resolves the target inside the Business: a request carries only a
 * LOCAL uid in the path; Meta's ids are never accepted, and a foreign uid is a
 * 404 with no provider call. View As is blocked for every route here by the
 * non-GET ads.* prohibition.
 *
 * The redirect target is NEVER taken from the request: it is generated by
 * route() from a re-whitelisted `from` (campaigns | campaign | ad-sets | ads)
 * and a re-validated `q` (list filters only). Provider text never reaches the
 * page: flashes are fixed platform copy.
 */
class MetaAdsMutationController extends CustomerBaseController
{
    use ResolvesBusinessTenancy;
    use ResolvesMetaAdsBusinessTenancy;

    private const UUID = '/\A[0-9a-fA-F\-]{36}\z/';

    public function __construct(
        private readonly WorkspaceRepository $workspaceRepository,
        private readonly WorkspaceManager $workspaceManager,
        private readonly MetaAdsMutationService $mutations,
    ) {
    }

    public function campaignPause(Request $request, string $workspaceUid, string $businessUid, string $campaignUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'campaigns.index', fn (Business $b, int $actor) => $this->mutations->pauseCampaign($b, null, $actor, $campaignUid));
    }

    public function campaignResume(Request $request, string $workspaceUid, string $businessUid, string $campaignUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'campaigns.index', fn (Business $b, int $actor) => $this->mutations->resumeCampaign($b, null, $actor, $campaignUid));
    }

    public function adSetPause(Request $request, string $workspaceUid, string $businessUid, string $adSetUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'ad-sets.index', fn (Business $b, int $actor) => $this->mutations->pauseAdSet($b, null, $actor, $adSetUid));
    }

    public function adSetResume(Request $request, string $workspaceUid, string $businessUid, string $adSetUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'ad-sets.index', fn (Business $b, int $actor) => $this->mutations->resumeAdSet($b, null, $actor, $adSetUid));
    }

    public function adPause(Request $request, string $workspaceUid, string $businessUid, string $adUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'ads.index', fn (Business $b, int $actor) => $this->mutations->pauseAd($b, null, $actor, $adUid));
    }

    public function adResume(Request $request, string $workspaceUid, string $businessUid, string $adUid): RedirectResponse
    {
        return $this->mutate($request, $workspaceUid, $businessUid, 'ads.index', fn (Business $b, int $actor) => $this->mutations->resumeAd($b, null, $actor, $adUid));
    }

    /**
     * @param  Closure(Business, int): MetaAdsMutationOutcome  $call
     */
    private function mutate(Request $request, string $workspaceUid, string $businessUid, string $fallbackRoute, Closure $call): RedirectResponse
    {
        [, $business] = $this->resolveMetaAdsModuleTenancy($workspaceUid, $businessUid);

        $this->authorize('manage_meta_ads');

        try {
            $outcome = $call($business, (int) Auth::id());
        } catch (MetaAdsMutationException $exception) {
            return $this->refused($exception, $request, $workspaceUid, $businessUid, $fallbackRoute);
        }

        return $this->returnTo($request, $workspaceUid, $businessUid, $fallbackRoute)->with($this->flash($outcome));
    }

    /**
     * A request the service refused before sending anything. Not found / not
     * entitled are bare 404s, a missing permission the application's 401; the
     * rest are calm messages in our own words.
     */
    private function refused(MetaAdsMutationException $exception, Request $request, string $workspaceUid, string $businessUid, string $fallbackRoute): RedirectResponse
    {
        abort_if($exception->httpStatus() === 404, 404);
        abort_if($exception->httpStatus() === 403, 401);

        $message = $exception instanceof MetaAdsMutationConnectionException && $exception->reason === MetaAdsMutationConnectionException::READ_ONLY
            ? 'Reconnect Meta to allow pause/resume.'
            : $exception->getMessage();

        return $this->returnTo($request, $workspaceUid, $businessUid, $fallbackRoute)->with($this->metaAdsFlash('error', $message));
    }

    /**
     * Fixed, calm copy per outcome. Provider text never reaches here:
     * MetaAdsMutationOutcome messages are the platform's own vocabulary.
     *
     * @return array{status: string, message: string, message_title?: string}
     */
    private function flash(MetaAdsMutationOutcome $outcome): array
    {
        return match ($outcome->status) {
            MetaAdsMutationOutcomeStatus::Succeeded => $this->metaAdsFlash('success', $outcome->message),
            MetaAdsMutationOutcomeStatus::AwaitingConfirmation => $this->metaAdsFlash(
                'warning',
                "Meta didn't confirm this change. We'll verify it on the next update. Nothing was changed twice.",
            ) + ['message_title' => 'Pending confirmation'],
            MetaAdsMutationOutcomeStatus::Deferred => $this->metaAdsFlash('warning', $outcome->message),
            MetaAdsMutationOutcomeStatus::Failed => $this->metaAdsFlash('error', $outcome->message),
            MetaAdsMutationOutcomeStatus::DuplicateNoop => $this->metaAdsFlash('info', $outcome->message),
        };
    }

    /** Back to the page the action came from, filters preserved, never an arbitrary URL. */
    private function returnTo(Request $request, string $workspaceUid, string $businessUid, string $fallbackRoute): RedirectResponse
    {
        $prefix = 'customer.workspaces.businesses.ads.meta.';
        $from = $request->input('from');
        $from = is_string($from) ? $from : null;
        $returnCampaign = $request->input('return_campaign');
        $query = MetaAdsListInput::returnQuery($this->parsedQuery($request));
        $base = [$workspaceUid, $businessUid];

        $url = match (true) {
            $from === 'campaign' && is_string($returnCampaign) && preg_match(self::UUID, $returnCampaign) === 1
                => route($prefix . 'campaigns.show', [...$base, $returnCampaign] + $query),
            $from === 'campaigns' => route($prefix . 'campaigns.index', $base + $query),
            $from === 'ad-sets' => route($prefix . 'ad-sets.index', $base + $query),
            $from === 'ads' => route($prefix . 'ads.index', $base + $query),
            default => route($prefix . $fallbackRoute, $base),
        };

        return redirect()->to($url);
    }

    /** @return array<string, mixed> */
    private function parsedQuery(Request $request): array
    {
        $raw = $request->input('q');
        $parsed = [];

        if (is_string($raw) && $raw !== '' && strlen($raw) <= 500) {
            parse_str($raw, $parsed);
        }

        return $parsed;
    }
}
