$CREATE_RELEASE()

cd $FORGE_RELEASE_DIRECTORY

export FORGE_PHP FORGE_COMPOSER FORGE_SITE_ROOT FORGE_SITE_BRANCH FORGE_RELEASE_DIRECTORY
bash deploy/forge/release-build.sh || exit 1

$ACTIVATE_RELEASE()

$RESTART_QUEUES()
